# Generated by Django 2.0.7 on 2018-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotografos'),
        ),
    ]
