# Generated by Django 2.0.7 on 2018-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Fotos_usuario'),
        ),
    ]
